2025-02-28 10:57:09,726 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 10:57:10,754 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 10:57:22,215 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 10:57:25,096 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A cadastrada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:47]
2025-02-28 10:57:29,540 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A atualizada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:104]
2025-02-28 10:57:31,599 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A desativada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:218]
2025-02-28 10:57:34,004 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A excluída com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:189]
2025-02-28 11:12:33,981 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:12:35,387 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:13:09,097 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:13:36,015 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:14:45,765 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:15:20,297 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:17:21,513 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:17:22,545 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:17:32,338 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 11:17:35,048 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A cadastrada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:49]
2025-02-28 11:17:39,482 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A atualizada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:104]
2025-02-28 11:17:41,537 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A desativada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:213]
2025-02-28 11:17:43,888 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A excluída com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:184]
2025-02-28 11:19:38,390 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 11:19:44,443 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 11:19:47,215 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A cadastrada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:49]
2025-02-28 11:19:51,642 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A atualizada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:104]
2025-02-28 11:19:53,707 INFO: Empresa EMPREENDIMENTOS PAGUE MENOS S/A desativada com sucesso. [in C:\prototipo\backend\app\services\empresa_service.py:213]
2025-02-28 11:30:27,919 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 13:51:56,342 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 13:52:45,375 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 13:54:52,109 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:08:26,955 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:08:50,744 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:10:54,243 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:12:07,119 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:13:24,893 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:13:25,950 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:13:43,805 ERROR: Erro ao processar emissão de NFC-e: Empresa com CNPJ 48144666000140 não encontrada [in C:\prototipo\backend\app\services\nfce\emissao_service.py:125]
2025-02-28 14:17:43,717 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:18:37,811 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:19:20,012 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:21:55,834 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:22:30,521 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:22:31,620 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:22:42,540 ERROR: Erro ao processar emissão de NFC-e: 'Endereco' object has no attribute 'codigo_municipio' [in C:\prototipo\backend\app\services\nfce\emissao_service.py:125]
2025-02-28 14:26:40,572 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:28:27,430 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:28:28,522 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:28:44,391 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:28:45,506 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:29:35,449 ERROR: Erro ao processar emissão de NFC-e: 'Endereco' object has no attribute 'codigo_municipio' [in C:\prototipo\backend\app\services\nfce\emissao_service.py:125]
2025-02-28 14:34:52,821 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:36:16,108 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:36:36,335 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:36:37,403 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-02-28 14:36:52,549 INFO: Emitindo NFC-e para empresa NUNES E BUSATO BARBEARIA LTDA [in C:\prototipo\backend\app\services\nfce\emissao_service.py:116]
2025-02-28 14:36:52,550 INFO: Enviando NFC-e para Nuvem Fiscal [in C:\prototipo\backend\app\services\nfce\factory_service.py:324]
2025-02-28 14:36:52,951 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 14:36:53,267 ERROR: Erro na requisição POST: 400 - {
    "error": {
        "code": "ValidationFailed",
        "message": "Validation failed: O campo 'infNFe.dest.CPF' deve ser um CPF válido",
        "errors": [
            {
                "code": "ValidationError",
                "message": "O campo 'infNFe.dest.CPF' deve ser um CPF válido"
            }
        ]
    }
} [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:246]
2025-02-28 14:36:53,272 ERROR: Erro ao emitir NFC-e: 'NoneType' object has no attribute 'get' [in C:\prototipo\backend\app\services\nfce\factory_service.py:329]
2025-02-28 14:36:53,314 INFO: NFC-e salva com sucesso. ID: 1, Chave: None [in C:\prototipo\backend\app\services\nfce\emissao_service.py:228]
2025-02-28 14:44:41,328 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-02-28 14:44:44,254 ERROR: Erro ao criar empresa: (sqlite3.IntegrityError) NOT NULL constraint failed: empresas.data_atualizacao
[SQL: INSERT INTO empresas (cpf_cnpj, inscricao_estadual, inscricao_municipal, nome_razao_social, nome_fantasia, email, telefone, data_cadastro, ativo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('06626253000151', '123456', '654321', 'EMPREENDIMENTOS PAGUE MENOS S/A', 'FARMÁCIAS PAGUE MENOS', 'contato@paguemenos.com.br', '8532553233', '2025-02-28 17:44:44.252233', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\prototipo\backend\app\services\empresa_service.py:53]
2025-02-28 14:44:44,255 ERROR: Erro ao criar empresa: (sqlite3.IntegrityError) NOT NULL constraint failed: empresas.data_atualizacao
[SQL: INSERT INTO empresas (cpf_cnpj, inscricao_estadual, inscricao_municipal, nome_razao_social, nome_fantasia, email, telefone, data_cadastro, ativo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('06626253000151', '123456', '654321', 'EMPREENDIMENTOS PAGUE MENOS S/A', 'FARMÁCIAS PAGUE MENOS', 'contato@paguemenos.com.br', '8532553233', '2025-02-28 17:44:44.252233', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\prototipo\backend\app\routes\empresa.py:106]
2025-03-03 10:31:51,629 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 10:31:52,741 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 10:32:32,243 INFO: Emitindo NFC-e para empresa NUNES E BUSATO BARBEARIA LTDA [in C:\prototipo\backend\app\services\nfce\emissao_service.py:116]
2025-03-03 10:32:32,244 INFO: Enviando NFC-e para Nuvem Fiscal [in C:\prototipo\backend\app\services\nfce\factory_service.py:324]
2025-03-03 10:32:32,579 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-03-03 10:32:32,924 ERROR: Erro na requisição POST: 400 - {
    "error": {
        "code": "ValidationFailed",
        "message": "Validation failed: O campo 'infNFe.dest.CPF' deve ser um CPF válido",
        "errors": [
            {
                "code": "ValidationError",
                "message": "O campo 'infNFe.dest.CPF' deve ser um CPF válido"
            }
        ]
    }
} [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:246]
