2025-03-03 10:38:33,701 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 10:38:35,181 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 10:39:08,520 INFO: Emitindo NFC-e para empresa NUNES E BUSATO BARBEARIA LTDA [in C:\prototipo\backend\app\services\nfce\emissao_service.py:116]
2025-03-03 10:39:08,521 INFO: Enviando NFC-e para Nuvem Fiscal [in C:\prototipo\backend\app\services\nfce\factory_service.py:328]
2025-03-03 10:39:08,858 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-03-03 10:39:10,438 INFO: NFC-e salva com sucesso. ID: 3, Chave: 31250348144666000140650010006149801383945894 [in C:\prototipo\backend\app\services\nfce\emissao_service.py:228]
2025-03-03 10:41:24,027 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 10:59:33,297 INFO: Emitindo NFC-e para empresa NUNES E BUSATO BARBEARIA LTDA [in C:\prototipo\backend\app\services\nfce\emissao_service.py:116]
2025-03-03 10:59:33,297 INFO: Enviando NFC-e para Nuvem Fiscal [in C:\prototipo\backend\app\services\nfce\factory_service.py:328]
2025-03-03 10:59:33,790 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-03-03 10:59:35,273 INFO: NFC-e salva com sucesso. ID: 4, Chave: 31250348144666000140650010000002841189727693 [in C:\prototipo\backend\app\services\nfce\emissao_service.py:228]
2025-03-03 11:15:39,602 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:16:10,902 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:19:14,206 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:20:16,676 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:22:06,907 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:22:25,805 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:22:26,856 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:22:53,300 INFO: Emitindo NFC-e para empresa NUNES E BUSATO BARBEARIA LTDA [in C:\prototipo\backend\app\services\nfce\emissao_service.py:102]
2025-03-03 11:22:53,300 INFO: Enviando NFC-e para Nuvem Fiscal [in C:\prototipo\backend\app\services\nfce\factory_service.py:347]
2025-03-03 11:22:53,760 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-03-03 11:22:54,959 INFO: NFC-e salva com sucesso. ID: 5, Chave: 31250348144666000140650010002107421107475934 [in C:\prototipo\backend\app\services\nfce\emissao_service.py:219]
2025-03-03 11:26:42,951 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:27:01,633 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
2025-03-03 11:46:47,822 INFO: Autenticação na Nuvem Fiscal realizada com sucesso [in C:\prototipo\backend\app\services\nuvem_fiscal\client.py:75]
2025-03-03 11:46:51,051 ERROR: Erro ao criar empresa: (sqlite3.IntegrityError) NOT NULL constraint failed: empresas.data_atualizacao
[SQL: INSERT INTO empresas (cpf_cnpj, inscricao_estadual, inscricao_municipal, nome_razao_social, nome_fantasia, email, telefone, data_cadastro, ativo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('06626253000151', '123456', '654321', 'EMPREENDIMENTOS PAGUE MENOS S/A', 'FARMÁCIAS PAGUE MENOS', 'contato@paguemenos.com.br', '8532553233', '2025-03-03 14:46:51.050202', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\prototipo\backend\app\services\empresa_service.py:53]
2025-03-03 11:46:51,052 ERROR: Erro ao criar empresa: (sqlite3.IntegrityError) NOT NULL constraint failed: empresas.data_atualizacao
[SQL: INSERT INTO empresas (cpf_cnpj, inscricao_estadual, inscricao_municipal, nome_razao_social, nome_fantasia, email, telefone, data_cadastro, ativo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('06626253000151', '123456', '654321', 'EMPREENDIMENTOS PAGUE MENOS S/A', 'FARMÁCIAS PAGUE MENOS', 'contato@paguemenos.com.br', '8532553233', '2025-03-03 14:46:51.050202', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\prototipo\backend\app\routes\empresa.py:106]
2025-03-03 15:07:17,432 INFO: Iniciando aplicação NFCe [in C:\prototipo\backend\app\__init__.py:63]
